### PR TITLE
Updated STXS workflow

### PR DESCRIPTION
**Pull request by edjtscott**
The main development of this PR is to update to STXS stage 1.2 and allow both the "usual" workflow and the ttH tag to be run together at the same time with systematics included. Inside the stage one customize function, the usual parallel systematics is used for all tags other than ttH, which have the modified systematics workflow already implemented. 

This also merges the latest developments of the ttH, tHq, and VH leptonic analysts, as well as the latest configurations for the ggH and qqH STXS categories. The ggH multi-class is *not* included, since its performance is not yet understood. 

There is still one remaining issue which should be solved before merging, related to the NNLOPS weights for ggH and having it propagated correctly to the systematic variations. The fix for that should come in the next few days. 

A separate PR will be made for the more granular JEC uncertainties, which I am also investigating now.

### CODE REVIEW

**Comment by edjtscott** [comment]
I think this is now ready to merge - @simonepigazzini or anyone else please let me know if you have comments

**Review by simonepigazzini — CHANGES_REQUESTED** [review]
Check data file paths

**Comment by edjtscott** [comment]
Paths should be correct now. Also have the option of the JEC uncertainty splitting added

**Comment by edjtscott** [comment]
Together with updates to the ggH, qqH, and ttH tags

**Review by simonepigazzini — APPROVED** [review]

**Pull request merged**
