### PR TITLE
New egm scale gain v1

### PR DESCRIPTION
**Pull request by shervin86**
- propagated EGM tool changes 
 - added methods to get the gain flag (to be used in python)
 - added two new nuisances (gain6 and gain1)

### CODE REVIEW

**Comment by shervin86** [comment]
I've checked that everything compiles, but not able to test it.
New .dat files from scale&smearing repository should also be added

**Comment by sethzenz** [comment]
@shervin86  OK, I'm working on testing now...  Just to be clear it's these two files we need, right?

https://raw.githubusercontent.com/ECALELFS/ScalesSmearings/master/Moriond17_74x_pho_scales.dat
https://raw.githubusercontent.com/ECALELFS/ScalesSmearings/master/Moriond17_74x_pho_smearings.dat

**Comment by shervin86** [comment]
I've not added them to the master yet. The files are:
https://raw.githubusercontent.com/ECALELFS/ScalesSmearings/master/Moriond17_74x_pho_scales.dat
https://raw.githubusercontent.com/ECALELFS/ScalesSmearings/master/Moriond17_74x_pho_smearings.dat

**Comment by sethzenz** [comment]
OK just for completeness (after discussion on Skype) the files I'll actually take are:
https://raw.githubusercontent.com/ECALELFS/ScalesSmearings/Moriond17_gainSwitch_unc/Moriond17_74x_pho_smearings.dat
https://raw.githubusercontent.com/ECALELFS/ScalesSmearings/Moriond17_gainSwitch_unc/Moriond17_74x_pho_scales.dat

**Comment by sethzenz** [comment]
Superseded by #899

**Pull request closed without merging**
