### PR TITLE
Changes needed to Run UL17

### PR DESCRIPTION
**Pull request by rchatter**
Tweaks needed to run with UL17:
Needs to be tested with DoubleEG data for workspace production.
Switched copying the S+S files from my git for now.

### CODE REVIEW

**Comment by rchatter** [comment]
@simonepigazzini @edjtscott please take a look.

**Comment by simonepigazzini** [comment]
Hi @rchatter, thanks a lot for this. 

@edjtscott in order for this to work one has to install flashgg from scratch since the EGamma package containing the s&s files has to be replaced. So please make sure this is advertise in the next meeting news. Once DoubleEG will be available I will also sent an email with detailed instruction to the working list.

Best,

simone

**Comment by edjtscott** [comment]
thanks both @rchatter @simonepigazzini - will include this in the news today

**Comment by rchatter** [comment]
> Hi @rchatter, thanks a lot for this.
> 
> @edjtscott in order for this to work one has to install flashgg from scratch since the EGamma package containing the s&s files has to be replaced. So please make sure this is advertise in the next meeting news. Once DoubleEG will be available I will also sent an email with detailed instruction to the working list.
> 
> Best,
> 
> simone

Hi Simone,

Yes either freshly cloning the EGM data git or alternately one can simply do:
############################################################
cd $CMSSW_BASE/src/EgammaAnalysis/ElectronTools/data
wget https://raw.githubusercontent.com/rchatter/EgammaAnalysis-ElectronTools/master/ScalesSmearings/Run2017_24Feb2020_runEtaR9Gain_v2_oldFormat_scales.dat
wget https://raw.githubusercontent.com/rchatter/EgammaAnalysis-ElectronTools/master/ScalesSmearings/Run2017_24Feb2020_runEtaR9Gain_v2_oldFormat_smearings.dat
cd $CMSSW_BASE/src
##################################################

**Pull request merged**
