### PR TITLE
Add MC signal and bkg. samples for tHq

### PR DESCRIPTION
**Pull request by gkrintir**
Hi Seth, 

Apart from the two signal samples, we also added bkg. ones that might be relevant. To save space, it's perfectly fine to apply a two photon skim on them. But centrally processing these additional bkg. samples is not a strict requirement from our side  ;D

Regards

### CODE REVIEW

**Comment by saghosh** [comment]
Hi @sethzenz , @gkrintir I notice that some of your (tHq) and our (ttH) backgrounds are similar and some files are repeated with this update (WGToLNuG, TTG, TT ). Perhaps you can remove the samples that are duplicated.

Another thing, I want to check the background from tHq to ttH categories (since I realise that it is a significant background for the ATLAS analysis). I just want to recheck if the samples for the tHq are all present in this update...

Thanks,
Saranya

**Comment by gkrintir** [comment]
Hi @saghosh I cannot see where the datasets are duplicated in the json we committed. ;D 

About the tHq samples, we included the ones that are currently available in miniAOD format. For the Moriond 17 campaign, there will be additionally:

THQ_ctcvcp_Hincl_13TeV-madgraph-pythia8_TuneCUETP8M1
THQ_ctcvcp_HToGG_13TeV-madgraph-pythia8_TuneCUETP8M1
THW_ctcvcp_Hincl_13TeV-madgraph-pythia8_TuneCUETP8M1
THW_ctcvcp_HToGG_13TeV-madgraph-pythia8_TuneCUETP8M1

But it's up to @sethzenz to decide whether they would be added, once they come, in the central production. ;D

**Comment by saghosh** [comment]
Hi @gkrintir thanks for listing the additional samples.
In the file : https://github.com/cms-analysis/flashgg/blob/master/MetaData/work/campaigns/RunIISpring16DR80X-2_3_0-25ns_PromptPostICHEP16_MiniAODv2.json

I see the following samples duplicated 

"/WGToLNuG_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM",
"/TTGJets_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8/RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1/MINIAODSIM"

It is probably because I had added those backgrounds in the previous commit.

**Comment by gkrintir** [comment]
Hi @saghosh , ah yeah right ;D

(Although the duplication doesn't translate to a duplication of cfg crab files with prepareCrabJobs since they are overwritten.)

Ok, can I make a new PR then @sethzenz removing the duplicates ? I prefer not to use the force push option and rebase.

**Comment by sethzenz** [comment]
Yes please make a PR, @gkrintir. cc @ferriff to be aware of potential duplication when submitting jobs.

**Pull request merged**
