### PR TITLE
Additional variables for b-jet regression

### PR DESCRIPTION
**Pull request by michelif**
Hi @sethzenz ,
this is an update of pull request #968 by @musella that you already merged before christmas for b-jet energy regression for HH->bbgg. During the review of the  a couple of extra variables were added. I updated the code here with them. Completely neglible changes on size and performance. It would be great if it's merged, so that we can test if everything is ok with the coming production. 
thanks

### CODE REVIEW

**Comment by sethzenz** [comment]
@michelif In principle the production is already started as a test (3_0_0), but I can integrate this and use it when submitting further jobs (3_0_1).   Then eventually if a rerun isn't required for another reason, we can go back and replace the 3_0_0 jobs with new 3_0_1's.  I'll work on that now.

In the meantime are there any other changes forseen for HH?  In particular, is there any special configuration to be done for signal samples?  At the moment they are labelled as background samples, hence no PDF information is propagated -- is this OK?   

Finally, can you let me know which MINIAODSIM samples would be high priority for testing this code?  Some HH signals I suppose, but please send the exact sample name(s).

**Comment by michelif** [comment]
Hi Seth, 
thanks. For the final analysis we need this on basically all samples (HH, diphoton, g+Jets, all single higgs, data, t(t)g(g)). It is not super-urgent anyway (we'll have a workshop next week, after that we will have a clearer time scale). For the moment, your idea to have some samples to see that everything and then go back to another reproduction of the samples is ok. 
The easiest sample for you to produce, useful for us, would be ZH since I have two photons and two jets with a mass peak. 
Of course the HH samples would be the best. The exact names looking on DAS are these ones [1], node_SM would be the one highest priority. I remember a mail exchange between you @andreypz and @dmajumder about running on these samples but I don't remember if the problem there was solved. I also let them comment about the PDF (naively I think we should have the PDF info).

[1] https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*GluGluToHHTo2B2G*node*%2FRunII*Fall17*%2F*MINIAOD*

thanks

**Comment by sethzenz** [comment]
OK.  I accept this pull request.  I'll launch tomorrow morning as is and include some HH samples.  I'll also include further HGG samples (since I only ran 125 so far).

**Comment by michelif** [comment]
With "all single higgs" I meant all process for M=125 (ggH, VBF, VH, ttH), different masses are not useful for us. thanks again.

**Comment by sethzenz** [comment]
Can you live with 126 for a while for testing purposes?  (I'm just try to avoid immediately rerunning exactly the same samples I already ran.)

**Comment by michelif** [comment]
yes, sure the phase space will not be so different

**Comment by dmajumder** [comment]
Hi, I'm not sure what PDF is used, apart from what's coded here:
https://github.com/cms-analysis/flashgg/blob/master/MicroAOD/python/flashggPDFWeightObject_cfi.py#L9

**Comment by sethzenz** [comment]
@michelif Please see #998 for a catalog containing this change.  Note that only some samples at 126 were available, but I also ran the HH sample.  Let me know if this is sufficient to test or if more is needed.

@dmajumder Some debugging is required to check it's the same pdf name in 2017 and make sure it runs as signal and is stored smoothly.  See also https://twiki.cern.ch/twiki/bin/viewauth/CMS/PDFatCMS   It would be helpful if someone ccan have a look.

**Pull request merged**
