### PR TITLE
conversion-tools-for-pat-ele-setup

### PR DESCRIPTION
**Pull request by InnaKucher**
Setup file with new method for pat electrons

### CODE REVIEW

**Comment by sethzenz** [comment]
The addition to the script builds ok, so this is fine.  However, no flashgg code uses the change yet.  So we will keep this request on hold until there's a PR for commits that need it.

**Comment by sethzenz** [comment]
Also just to note: at some point a text editor (in Windows?) touched this file that added a '\r' character at the end of every line, causing the diffs to claim every line changed even though only a few lines were added.   Best to avoid this if possible; it can be checked by diffing and seeing if the whole file is changed.

**Comment by InnaKucher** [comment]
It is not Windows, I use Linux and usually edit files with vim. Ok, I will check files in future, thanks.

**Comment by sethzenz** [comment]
See #180 for discussion of how to fix the extra character and preserve history

**Pull request closed without merging**
