### PR TITLE
Update to 2017 V32 94X JECs, switch to reading from FrontierProd

### PR DESCRIPTION
**Pull request by sam-may**
Updates to switch to 17Nov2017 V32 JECs. Both MicroAOD production and workspace production should be updated to reflect the new JECs.

JECs are now read from FrontierProd db instead of relying on the sqlite db files.

@simonepigazzini , let me know if everything looks properly migrated to the FrontierProd db files.

### CODE REVIEW

**Comment by malcles** [comment]
Dear Simone and Samuel,

can you please tell me what is the status of these JEC corrections? Has this implementation been tested technically?
It would be nice if Ed could add them to the STXS upcoming result. Probably he can get them back directly from this PR.

Cheers,

Julie



On Dec 17, 2018, at 23:42, Samuel May <notifications@github.com<mailto:notifications@github.com>> wrote:


Updates to switch to 17Nov2017 V32 JECs. Both MicroAOD production and workspace production should be updated to reflect the new JECs.

JECs are now read from FrontierProd db instead of relying on the sqlite db files.

@simonepigazzini<https://github.com/simonepigazzini> , let me know if everything looks properly migrated to the FrontierProd db files.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/cms-analysis/flashgg/pull/1091

Commit Summary

  *   Update to 2017 V32 94X JECs
  *   Remove sqlite JEC files
  *   Switch to reading JEC from FrontierProd db instead of sqlite files

File Changes

  *   M MicroAOD/python/MicroAODCustomize.py<https://github.com/cms-analysis/flashgg/pull/1091/files#diff-0> (6)
  *   M MicroAOD/python/flashggJetTools_cfi.py<https://github.com/cms-analysis/flashgg/pull/1091/files#diff-1> (3)
  *   M MicroAOD/python/flashggMETs_cff.py<https://github.com/cms-analysis/flashgg/pull/1091/files#diff-2> (3)
  *   M MicroAOD/python/flashggMet_RunCorrectionAndUncertainties_cff.py<https://github.com/cms-analysis/flashgg/pull/1091/files#diff-3> (3)
  *   M MicroAOD/test/microAODstd.py<https://github.com/cms-analysis/flashgg/pull/1091/files#diff-4> (7)
  *   M Systematics/python/SystematicsCustomize.py<https://github.com/cms-analysis/flashgg/pull/1091/files#diff-5> (5)
  *   M Systematics/python/flashggJetSystematics_cfi.py<https://github.com/cms-analysis/flashgg/pull/1091/files#diff-6> (12)
  *   M Systematics/test/workspaceStd.py<https://github.com/cms-analysis/flashgg/pull/1091/files#diff-7> (2)

Patch Links:

  *   https://github.com/cms-analysis/flashgg/pull/1091.patch
  *   https://github.com/cms-analysis/flashgg/pull/1091.diff

**Comment by simonepigazzini** [comment]
Dear @malcles ,

the PR works so Ed can merge it in his own working branch. I merged this into the "future" master to run on all three years and I will probably close this PR at some point.

simone

**Comment by edjtscott** [comment]
Hi Simone, all,

Thanks for confirming it works - I will incorporate it into the next set of workspaces.

Cheers,
Ed


On 14 Jan 2019, at 09:53, simonepigazzini <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @malcles<https://github.com/malcles> ,

the PR works so Ed can merge it in his own working branch. I merged this into the "future" master to run on all three years and I will probably close this PR at some point.

simone

**Comment by simonepigazzini** [comment]
Manually merged into dev_legacy_runII through:

https://github.com/cms-analysis/flashgg/pull/1093

**Pull request closed without merging**
