### PR TITLE
hooks + scripts + VHEtTag indentation

### PR DESCRIPTION
**Pull request by camilocarrillo**
This pull request includes the hooks for indentation, please test before merging. 

Every time the user executes "git commit" a script will check the local files for indentation. If a mismatch is found the commit is aborted. If the indentation is fine the commit is done.

The automatic indentation script was modified to shows the amount of files it proposes to change to the user, and it is up to the user to accept or not the changes.

The check for indentation could be skipped with the flag --no-verify 

Finally some recently merged files for VHEtTag are corrected to comply with the agreed indentation.

### CODE REVIEW

**Comment by sethzenz** [comment]
This looks good to me.  I'll do some tests and checks today, and give a little more time in case anyone else has comments or suggestions.

**Comment by sethzenz** [comment]
Hmmm...   The automatic check script found 5 files that needed to be changed.  Then I ran the indent script as recommended and it found more than 5, and then it had some errors:

[sethzenz@lxplus0207]/afs/cern.ch/work/s/sethzenz/fromscratch19/CMSSW_7_4_0_pre9/src/flashgg% ./Validation/scripts/flashgg_indent.sh 
You are about to change 15 files due to indentation
./MicroAOD/plugins/DiPhotonProducer.cc
./MicroAOD/plugins/LegacyVertexSelector.cc
./MicroAOD/plugins/StdIsolationAlgo.cc
./Taggers/plugins/DiPhotonMVAProducer.cc
./Validation/plugins/vertexProbTrainingTreeMaker.cc
./MicroAOD/plugins/DiPhotonProducer.cc
./MicroAOD/plugins/LegacyVertexSelector.cc
./MicroAOD/plugins/StdIsolationAlgo.cc
./Taggers/plugins/DiPhotonMVAProducer.cc
./Validation/plugins/vertexProbTrainingTreeMaker.cc
./MicroAOD/plugins/DiPhotonProducer.cc
./MicroAOD/plugins/LegacyVertexSelector.cc
./MicroAOD/plugins/StdIsolationAlgo.cc
./Taggers/plugins/DiPhotonMVAProducer.cc
./Validation/plugins/vertexProbTrainingTreeMaker.cc
Do you want to continue? (Y/N) y
rm: cannot remove `./MicroAOD/plugins/DiPhotonProducer.cc.orig': No such file or directory
rm: cannot remove `./MicroAOD/plugins/LegacyVertexSelector.cc.orig': No such file or directory
rm: cannot remove `./MicroAOD/plugins/StdIsolationAlgo.cc.orig': No such file or directory
rm: cannot remove `./Taggers/plugins/DiPhotonMVAProducer.cc.orig': No such file or directory
rm: cannot remove `./Validation/plugins/vertexProbTrainingTreeMaker.cc.orig': No such file or directory
rm: cannot remove `./MicroAOD/plugins/DiPhotonProducer.cc.orig': No such file or directory
rm: cannot remove `./MicroAOD/plugins/LegacyVertexSelector.cc.orig': No such file or directory
rm: cannot remove `./MicroAOD/plugins/StdIsolationAlgo.cc.orig': No such file or directory
rm: cannot remove `./Taggers/plugins/DiPhotonMVAProducer.cc.orig': No such file or directory
rm: cannot remove `./Validation/plugins/vertexProbTrainingTreeMaker.cc.orig': No such file or directory

**Comment by sethzenz** [comment]
You should be able to reproduce the issue above by checking out the current upstream/master and merging this branch in... then committing anything.

**Comment by camilocarrillo** [comment]
Hi, we were missing some paths in the scripts, I have corrected and updated the master and pull request.

**Pull request merged**
