### PR TITLE
Fix the muon SF for UL and tag names for Jet Resolution in 2016 UL 

### PR DESCRIPTION
**Pull request by emanueledimarco**
* muon SFs are for 2016 vs abs(eta)
* fix typo in the tag names for 2016 preVFP and post VFP JR

### CODE REVIEW

**Comment by youyingli** [comment]
To remove the eta extension part should be suitable as we have taken the absolute value to muon eta.

**Comment by emanueledimarco** [comment]
Yes this is what I did I think in the last commit [38c7368](https://github.com/cms-analysis/flashgg/pull/1293/commits/38c7368b1e472e98d945611bfbc3e65cd485dabf), no?

**Comment by youyingli** [comment]
Sorry for the late review. Your modification could still create some useless negative-eta bins as the muon now take the absolute value. You should remove L92-L99, L123-L130, L139-L146, L156-L163, L198 and modify L101 back to 
```pt_bins[ pt_from ] =  self.binInfo.bins[-1]```
and L165-L166 back to
```pt_bins[ sorted(pt_bins.keys())[-1] ].upBounds[1] = float( 'inf' )```.

**Comment by JunquanTao** [comment]
Hi Youying @youyingli , I have also sumitted a PR severals ago and do some changes on the file "flashggMuonSystematics_cfi.py". Please review it. Thanks, Junquan
[1] https://github.com/cms-analysis/flashgg/pull/1295

**Comment by emanueledimarco** [comment]
@youyingli thanks, I didn't notice those pieces. Should be removed now.

**Comment by youyingli** [comment]
@emanueledimarco thanks. Merged!

**Pull request merged**
