### PR TITLE
Updated UL16 scales and smearings to stochastic

### PR DESCRIPTION
**Pull request by neilSchroeder**

### CODE REVIEW

**Comment by JunquanTao** [comment]
Hi Neil, where we can find these scaling and smearing files EgammaAnalysis/ElectronTools/data/ScalesSmearings/Run2016_2021-07-07_postVFP_stochastic_oldFormat* ? You need to put them in https://github.com/rchatter/EgammaAnalysis-ElectronTools.git. Then people can check out these files with https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/setup_flashgg.sh#L54 . Right? Thanks, Junquan

**Comment by JunquanTao** [comment]
Hi all, Rajdeep just committed the UL16 ET dependent scales and smearings to his github repos. [1].  So the changes in this PR should work fine now.  Thanks, Junquan
[1] https://github.com/rchatter/EgammaAnalysis-ElectronTools/commit/a7ed824d4ffbd6dfc884b2a06da7ae6b1c4db889

**Comment by youyingli** [comment]
Hi @JunquanTao, @neilSchroeder, #1295 cover this PR which would be fine to close?

**Comment by JunquanTao** [comment]
Hi @youyingli, I think so. @neilSchroeder  should confirm this.

**Comment by neilSchroeder** [comment]
Hi @JunquanTao and @youyingli, the scales and smearing listed in #1295 are an older version of the scales that are not Et dependent, so I do not think this is ready to close.

**Comment by JunquanTao** [comment]
Hi @neilSchroeder , the paths were updated. Can you please check https://github.com/cms-analysis/flashgg/pull/1295 again. Thanks, Junquan

**Comment by neilSchroeder** [comment]
Hi yes, I see now. I will close this.

**Pull request closed without merging**
