### PR TITLE
Fix B Tag weight for low pT jets

### PR DESCRIPTION
**Pull request by saghosh**
Updating to remove bug for b and c jets between 25 and 30 GeV

### CODE REVIEW

**Comment by sethzenz** [comment]
We still get a 0 weight event, later in root://eoscms.cern.ch//eos/cms//store/group/phys_higgs/cmshgg/ferriff/flashgg/RunIIFall15DR76-1_3_0-25ns_ext1/1_3_1/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspi\
n_pythia8/RunIIFall15DR76-1_3_0-25ns_ext1-1_3_1-v0-RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/160127_024939/0000/myMicroAODOutputFile_1.root than before...

Begin processing the 4501st record. Run 1, Event 384785, LumiSection 1967 at 10-Mar-2016 12:03:20.997 CET
----- Begin Fatal Exception 10-Mar-2016 12:03:23 CET-----------------------
An exception of category 'TagObjectWeight' occurred while
   [0] Processing run: 1 lumi: 1982 event: 387736
   [1] Running path 'p'
   [2] Calling event method for module FlashggTagSorter/'flashggTagSorter'
Exception Message:
 Tag centralWeight=0 outside of bound [0.1,10] - flashggTTHHadronicTag chosenIndex=0 - change bounds or debug tag
----- End Fatal Exception -------------------------------------------------

I am investigating now if it is from BTag or something else.

**Comment by sethzenz** [comment]
The catch for the high end is not working!

 In JetBTagWeight after obtaining SF: JetBTagWeightCentral: Object has pt= 753.335 eta=1.05688 flavour=5 efficiency of 0.554314 scale factors : 0 0 0
 In JetBTagWeight : JetBTagWeightCentral: Object has pt= 753.335 eta=1.05688 flavour=5 efficiency of 0.554314 scale factors : 0 0 0

**Comment by sethzenz** [comment]
I think this is the fix:
-            float MaxBJetPt = 670., MaxLJetPt = 1000.;
+            float MaxBJetPt = 669.9, MaxLJetPt = 1000.;

**Comment by saghosh** [comment]
Hi,

Yes, for the low pT i fixed it to 30.01 and 20.01 for such cases, I will
change the high pT too to something like that and send it.

With regards,
Saranya Ghosh

**Comment by saghosh** [comment]
Hi Seth, I changed the maximum jet pT numbers, hope it works now. Please let me know. Thanks,

With regards,
Saranya Ghosh

**Comment by sethzenz** [comment]
Yes I believe this is now fixed.  Thanks for your quick work, @saghosh!

**Pull request merged**
