### PR TITLE
update to CMSSW_8_0_26_patch1, split off uAOD recipes into bigger set…

### PR DESCRIPTION
**Pull request by sethzenz**
…up file

### CODE REVIEW

**Comment by ferriff** [comment]
Hi,

I don't think it is a good idea to split recipes for uAOD production
and post-uAOD processing. It is yet one more hassle for people doing
analysis and/or needing from time to time to independently produce and
look at uAODs.

Why should this be needed? Do we really gain so much by having this split?

I feel we are diverging towards complications.

My 2 cents,
Federico

**Comment by sethzenz** [comment]
The problem is branches out of our control that check out too many packages especially as the release number advances.  Below are the current lists without and with uAOD support included.  I have also emailed some of the people responsible for the recipes but I do not know if a fix will come soon.

with setup.sh

[sethzenz@lxplus0048]/afs/cern.ch/work/s/sethzenz/fromscratch138/CMSSW_8_0_26_patch1/src% ll
drwxr-xr-x. 3 sethzenz zh 2048 Feb  9 20:59 CommonTools
drwxr-xr-x. 4 sethzenz zh 2048 Feb  9 20:59 DataFormats
drwxr-xr-x. 3 sethzenz zh 2048 Feb  9 20:59 EgammaAnalysis
drwxr-xr-x. 3 sethzenz zh 2048 Feb  9 21:00 FWCore
drwxr-xr-x. 3 sethzenz zh 2048 Feb  9 21:00 GeneratorInterface
drwxr-xr-x. 3 sethzenz zh 2048 Feb  9 20:59 PhysicsTools
drwxr-xr-x. 3 sethzenz zh 2048 Feb  9 20:59 RecoEgamma
drwxr-xr-x. 3 sethzenz zh 2048 Feb  9 20:58 RecoJets
drwxr-xr-x. 3 sethzenz zh 2048 Feb  9 20:58 RecoMET
drwxr-xr-x. 9 sethzenz zh 2048 Feb  9 21:00 flashgg

with setup_includingMicroAOD.sh

[sethzenz@lxplus0048]/afs/cern.ch/work/s/sethzenz/fromscratch137/CMSSW_8_0_26_patch1/src% ls -lrth
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 20:58 RecoJets
drwxr-xr-x. 5 sethzenz zh 2.0K Feb  9 20:59 RecoMET
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 20:59 CalibMuon
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 20:59 TopQuarkAnalysis
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 20:59 DQMOffline
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 20:59 Configuration
drwxr-xr-x. 5 sethzenz zh 2.0K Feb  9 21:00 DataFormats
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:00 EgammaAnalysis
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:01 GeneratorInterface
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:01 FWCore
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:02 Calibration
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:02 RecoBTag
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:02 HLTriggerOffline
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:02 DQMServices
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:02 DQM
drwxr-xr-x. 5 sethzenz zh 2.0K Feb  9 21:02 CommonTools
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:02 Validation
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:02 RecoHI
drwxr-xr-x. 7 sethzenz zh 2.0K Feb  9 21:02 RecoEgamma
drwxr-xr-x. 6 sethzenz zh 2.0K Feb  9 21:02 PhysicsTools
drwxr-xr-x. 3 sethzenz zh 2.0K Feb  9 21:03 L1Trigger
drwxr-xr-x. 9 sethzenz zh 2.0K Feb  9 21:03 flashgg

**Comment by sethzenz** [comment]
Update for the record: https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1861/1.html

**Comment by sethzenz** [comment]
Superseded by #843

**Pull request closed without merging**
