### PR TITLE
Generic code for histograms, trees and dataset creation

### PR DESCRIPTION
**Pull request by musella**
- Imported template CollectionDumper class and (Di)Photon(Tag) specializations.
- Implemeted PluggableAnalyzer to run generic fwlite analyzers.
- Also imported Phy14 samples catalog.

### CODE REVIEW

**Comment by sethzenz** [comment]
Does not interfere with existing code. Builds OK, MicroAOD and Tag producer tests ok.  However I'm not sure how to give an appropriate input to TagAlgos/test/diphotonsDumper.py in order to test that, but that's fine for now.

**Comment by musella** [comment]
Hi,

I forgot to commit the test file. I will do it asap. 

Apologies, 
Pasquale

**Comment by ldcorpe** [comment]
Hi Pasquale,
 
I was going to have a look at this to see if I could get it running. Have you had a chance to commit the test file/some instruction for the above?

All the best,

Louie

**Comment by musella** [comment]
Hi,

in fact I realized that everything is committed.

Have a look at this readme for the instructions on how to use the MetaData
machinery.

https://github.com/cms-analysis/flashgg/tree/master/MetaData

All you need to run the test, you have everything here:

https://github.com/cms-analysis/flashgg/tree/master/TagAlgos/test


commandline to run is:

fggRunJobs.py
<https://github.com/cms-analysis/flashgg/tree/master/MetaDatafggRunJobs.py>
--load higPhys14samples.json -d test_dipho
./diphotonsDumper.py maxEvents=10

Cheers,
P.




On 29 January 2015 at 17:06, ldcorpe <notifications@github.com> wrote:

> Hi Pasquale,
>
> I was going to have a look at this to see if I could get it running. Have
> you had a chance to commit the test file/some instruction for the above?
>
> All the best,
>
> Louie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-analysis/flashgg/pull/149#issuecomment-72050691>.
>



-- 
Pasquale Musella - ETHZ
http://musella.web.cern.ch/musella

**Pull request merged**
