### PR TITLE
Update the VH Leptonic Tags under the STXS framework for UL version

### PR DESCRIPTION
**Pull request by youyingli**
Hi @edjtscott , here is the VH Leptonic Tags under the STXS framework for UL version. Note that the WH Leptonic tag is divided 3 STXS bins with ptV = 0_75,   75_150, >150.

There is no problem in my local test. However, could you please cross check when you pull to your branch?  Thanks a lot!

MVA training information
https://indico.cern.ch/event/961163/contributions/4070079/attachments/2125730/3578901/HggMeeting_19102020.pdf

MVA Boundary optimization
https://indico.cern.ch/event/961183/contributions/4079360/attachments/2129857/3586825/HggMeeting_26102020.pdf

### CODE REVIEW

**Comment by edjtscott** [comment]
hi @youyingli, thanks a lot - I will test this week and let you know 👍

**Comment by edjtscott** [comment]
If you can add the link to the slides you recently presented that would also be handy

**Comment by edjtscott** [comment]
@youyingli tested this out, seems to work fine!

**Comment by youyingli** [comment]
Hi @edjtscott , thanks for the check. I think this PR should be merged to the PR which combines all STXS update from your side. So I think this PR can be closed after you make the PR about all STXS update. How do you think?

**Comment by edjtscott** [comment]
hi You-Ying, yes I agree, all the STXS updates can come together. We can leave this open until I make the final STXS PR 👍

**Comment by edjtscott** [comment]
Incorporated into PR 1272, will now close this one

**Pull request closed without merging**
