### PR TITLE
Update to 2017 V32 94X JECs

### PR DESCRIPTION
**Pull request by sam-may**
Updates to switch to 17Nov2017 V32 JECs. Both MicroAOD production and workspace production should be updated to reflect the new JECs.

### CODE REVIEW

**Comment by simonepigazzini** [comment]
Thanks @sam-may. Is there a reason to rely on sqlite files instead of reading the tag from the FrontierProd db? If not can you please switch to the db and remove the sqlite files form the repo.

simone

**Comment by sam-may** [comment]
Hi @simonepigazzini , I have no reason to prefer either method -- I uploaded the .db files to `Systematics/data/JEC/` just because I saw that the V6 files had been uploaded.

To make sure I understand, you're just proposing I create a new PR without the .db files included in the commit?

**Comment by simonepigazzini** [comment]
Yes please make a new PR adjusting the config files and without the files in the commit. I am closing this one.

Thank you,

simone

**Comment by simonepigazzini** [comment]
https://github.com/sam-may/flashgg/blob/f04af069f4e281f01dd898c5ab6411e55baace81/Systematics/python/SystematicsCustomize.py#L227

Instead of "sqlite ..." put "frontier://FrontierProd/CMS_CONDITIONS"

take a look also at this branch https://github.com/chernyavskaya/flashgg/blob/hh_tag_94X_20181130/Systematics/python/flashggJetSystematics_cfi.py#L271 for the other occurences.

simone

**Pull request closed without merging**
