### PR TITLE
Update UL 17 ingredients

### PR DESCRIPTION
**Pull request by edjtscott**
This PR designed to include the required updates for the UL 17 dataset. So far just updates the photon systematics file in the MetaConditions (previously not set to the legacy version) and adds the databases needed for the JEC and JER (not yet included in any global tag). 

Expect additional commits from @rchatter but these two aspects should be the most important ones for anyone hoping to run ntuples asap.

### CODE REVIEW

**Comment by rchatter** [comment]
Hi,
The commits that are expected but pending are the following
1) Electron ID SFs : need to create a combined JSON of ID SFs. Have located Francesco's code and instructions (https://indico.cern.ch/event/842077/contributions/3633040/attachments/1941671/3219683/egm_08Nov19.pdf and https://github.com/michelif/json_converter_egID). Trying to get it running.
2) Muon ID SFs : Missing the low pt ID SFs. Following up with Muon POG https://hypernews.cern.ch/HyperNews/CMS/get/muon/1666/1.html
3) B Tag  SFs missing for UL 17 : Following up with BTV POG https://hypernews.cern.ch/HyperNews/CMS/get/btag/1809.html

Rajdeep

**Comment by simonepigazzini** [comment]
@edjtscott are you sure that the JEC and JER are not available through Frontier and only through the sqlite file?

**Comment by edjtscott** [comment]
In the tables [here](https://twiki.cern.ch/twiki/bin/viewauth/CMS/JECDataMC) it says the GT with these corrections is tba, which is why I added them by hand

**Comment by edjtscott** [comment]
@simonepigazzini I now tried reverting to frontier, as we discussed.  It seems that the JEC are there but not the JER; I'm currently getting an error `Tag "JR_Summer19UL17_JRV2_MC_PtResolution_AK4PFchs" has not been found in the database.`

So if OK with you I will leave it as-is for now?

**Comment by simonepigazzini** [comment]
Ok fine. I will blame JME for sinking my masterplane of reading everything from db

**Comment by edjtscott** [comment]
hi all (@simonepigazzini @youyingli @zhangyu0217), this PR should now be complete from our side. Could you double check it all looks sensible before merging? Thanks a lot

**Review by youyingli — APPROVED** [review]
After checking, they are totally up to date and available. I agree to merge !

**Pull request merged**
