### PR TITLE
Catalog for UL16preVFP & UL2018

### PR DESCRIPTION
**Pull request by ram1123**

### CODE REVIEW

**Comment by youyingli** [comment]
Hi @ram1123 , could you please resolve the conflicts in the two files? For ```MetaData/data/RunIISummer20UL16postVFP/datasets.json```, I think you only need to change the file name ```datasets.json``` to ```datasets_8.json``` and for ```MetaData/work/prepareCrabJobs.py```, you could need to modify the python list ```replacements```  at L265 I think.

**Comment by Prasant1993** [comment]
Hii @youyingli, 
 I see the UL16 datasets for Pre/PostVFP era in Summer20 Campaign is not merged yet. 
 I was producing the ntuples using the Summer19 campaign without knowing the Summer20UL campaign exists, but I am facing file open error mostly for the SingleElectron  datasets in this Summer19 campaign.  
Are all the possible checks passed for this PR ?
Can it be merged soon?

Thanks,
Prasant

**Comment by youyingli** [comment]
Hi @Prasant1993 , since this PR has some conflicts, now I copy the UL16 and UL18 campaign parts in this PR to #1298 and it's merged.

**Comment by Prasant1993** [comment]
Thanks @youyingli

**Comment by ram1123** [comment]
Hi @youyingli 

I am sorry; I just checked the messages on GitHub after Rajdeep messaged me.

Somehow all my messages from GitHub were archived by default, so I didn't see your messages.

Now, I resolved the merge conflicts. If you think this is still useful, you can merge it or close it.

Sorry for missing your messages.

**Comment by neilSchroeder** [comment]
Hello, is there updates on this? I'd like to start using some of the information in this PR.

**Comment by youyingli** [comment]
Hi @neilSchroeder , thanks for the reminder. If you would like to use the campaigns for UL16preVFP & UL2018, #1298 has covered all. If not, before merging, @ram1123 , make sure if you change the data format for flashgg::Met, otherwise why the classes_def.xml is altered in this PR?

**Comment by neilSchroeder** [comment]
Ah yes. Thank you for pointing this out to me. The source of my confusion was the new naming convention for the campaigns, but it's clear to me now.

**Comment by ram1123** [comment]
@youyingli 
> why the classes_def.xml is altered in this PR?

While compiling the flashgg version, it complained and said to update the ClassVersion. So, I just copied and pasted whatever CMSSW suggested.

**Comment by youyingli** [comment]
Hi @ram1123 , the ClassVersion should not be changed in current flashgg after I tested locally. From this PR, I accidentally found some issues in "Era2017_legacy_v1_Summer20UL" and "RunIISummer20UL16postVFP" campaigns which need to be fixed. OK, I still close this PR. Thanks for your contribution.

**Pull request closed without merging**
