### PR TITLE
Adding UL16 post-VFP samples catalog

### PR DESCRIPTION
**Pull request by emanueledimarco**
This replaces the PR #1289, with only the commit adding the post-VFP samples. 
The samples are wrongly named campaign "Summer20UL18", and this appears in DAS name. Please ignore this wrong name, the conditions used are the right ones for **Summer20UL16**. 

I will now close the PR #1289, and maybe reopen it later with only analysis-level changes. 

@mhl0116 @youyingli @ram1123

### CODE REVIEW

**Comment by youyingli** [comment]
Hi @emanueledimarco, 

- Although the file names for UL16 post-VFP have a typo (Summer20UL18), you still need to put these JSONs to "RunIISummer20UL16postVFP" directory not "RunIISummer20UL18" to avoid the program pointing to "Summer20UL18" configurations when running fggRunJobs.py.

- Not only 
`fggManageSample.py -C yourCampaign import -S yourDatasetname_withDASformat `
to create a catalog with several JSON files, you could also need to run 
`fggManageSample.py -C yourCampaign check -S yourDatasetname_withDASformat`
to this catalog to get the sum of genweight for each file recorded in the same JSON files.

**Comment by emanueledimarco** [comment]
@youyingli ok changed the name of the directory and running  the check. Will update the PR afterwards. On the `check` step, I get some "connect localhost port 6010: Connection refused" message, even if I have a valid proxy. It seems some temporary glitch, but just to make sure it is something that others also get

**Comment by emanueledimarco** [comment]
@youyingli done (commit [ebedc28](https://github.com/cms-analysis/flashgg/pull/1290/commits/ebedc28f06c1a7ec58ccbd7bdcf521146c171e6b))  for the samples fully done. 
Will update again the PR with the few missing samples for the mass measurement.

**Comment by emanueledimarco** [comment]
Sorry, I again merged my developments in this branch. Will try to clean it up leaving only the commits relative to the samples

**Comment by emanueledimarco** [comment]
Closing this in favor of the new #1292 which replaces this one.

**Pull request closed without merging**
