### PR TITLE
Including Bad Muon Filters in FLASHgg

### PR DESCRIPTION
**Pull request by saghosh**

### CODE REVIEW

**Comment by sethzenz** [comment]
@saghosh This PR crashes because this line specifies an object that doesn't exist: https://github.com/cms-analysis/flashgg/pull/807/files#diff-52f0a0396e085a6074b1f1666ca6c017R369   If you see this soon, please send me a message with the fix.  (Otherwise trying to guess.)

**Comment by saghosh** [comment]
Hi Seth,
I had added a line to the setup.sh

https://github.com/cms-analysis/flashgg/pull/807/files#diff-6aa367da3fdfc952b15def7759aa5f0bR125

it's supposed to merge the code from giovanni and the config file as well.
scram b 
after that worked for me..

**Comment by sethzenz** [comment]
@saghosh I got that change, but I'm afraid it's a python issue.  You have 

        process.dataRequirements += noBadGlobalMuons

But I think I need:

        process.dataRequirements += process.noBadGlobalMuons

I'm still verifying this change has the intended effect.

**Comment by saghosh** [comment]
Hi yes that must be it. I think it must be because of two files that I was testing it on and I committed the different one.
I will commit the correct one again.

**Comment by sethzenz** [comment]
@saghosh Thanks.  Can you also suggest a useful file to test on that has some muons that fail the filter?

**Comment by saghosh** [comment]
Hi Seth,

This file works :

"root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/cmshgg/ferriff/flashgg/RunIISpring16DR80X-2_3_0-25ns_Moriond17_MiniAODv2/2_3_0/DoubleEG/RunIISpring16DR80X-2_3_0-25ns_Moriond17_MiniAODv2-2_3_0-v0-Run2016C-23Sep2016-v1/161201_231641/0000/myMicroAODOutputFile_101.root"

you will get a print of 
https://github.com/gpetruc/cmssw/blob/badMuonFilters_80X_v2/RecoMET/METFilters/plugins/BadGlobalMuonTagger.cc#L103-L112

the verbose mode is on by default in Giovanni's code

**Comment by saghosh** [comment]
@sethzenz please see 
https://github.com/cms-analysis/flashgg/pull/810
PR810

Somehow git was causing some problems and I had to use a different branch.

**Pull request closed without merging**
