### PR TITLE
Updated e-veto SFs, metaConditions and other modifications for UL16

### PR DESCRIPTION
**Pull request by JunquanTao**

### CODE REVIEW

**Comment by youyingli** [comment]
Hi @JunquanTao, after discussing with @emanueledimarco in #1293 ,

for ```flashggElectronSystematics_cfi.py```, I found the electron systematics source is wrong. The bug was fixed a few days ago and now the electron pt for all years is up to 500GeV. Hence, the file doesn't need to be modified.

for ```flashggMuonSystematics_cfi.py```, we also hope to remove minus eta extension codes and modify [flashggMuonSystematics_cfi.py L15](https://github.com/cms-analysis/flashgg/blob/00a088ac0a6caae69afe257e9129ab8879e60a4a/Systematics/python/flashggMuonSystematics_cfi.py#L15) from ```eta``` to ```abs(eta)``` as now the muon systematics source is always absolute eta.

**Comment by JunquanTao** [comment]
Hi @youyingli  thanks for the comments on these two files, flashggElectronSystematics_cfi.py and flashggMuonSystematics_cfi.py.  I just kept these two files to be the original ones. For the file "flashggMuonSystematics_cfi.py", you can merge teh changes from https://github.com/cms-analysis/flashgg/pull/1293. Thanks, Junquan

**Comment by youyingli** [comment]
Hi @JunquanTao, thanks. Please also keep the JER to the original one as #1293 has fixed it.

**Comment by JunquanTao** [comment]
Hi @youyingli, " Please also keep the JER to the original one" --> Done. JT

**Comment by Prasant1993** [comment]
Hii @youyingli, I need this PR for the preselection and IDMVA SF measurements for UL2016. If all things are reviewed, can you please merge this PR. So that I can initiate the study. 

Thanks,
Prasant

**Pull request merged**
