### PR TITLE
Add HHWWgammagamma samples to RR catalogues

### PR DESCRIPTION
**Pull request by alesauva**
adding to the RR 2016, 2017 and 2018 catalogues HHWWgammagamma samples:
-GluGluToHHTo2G2l2nu_node_10_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_11_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_12_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_1_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_2_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_3_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_4_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_5_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_6_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_7_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_8_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_9_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_SM_TuneCUETP8M1_PSWeights_13TeV-madgraph-pythia8
-GluGluToHHTo2G2l2nu_node_cHHH0_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8
-GluGluToHHTo2G2l2nu_node_cHHH1_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8
-GluGluToHHTo2G2l2nu_node_cHHH5_TuneCUETP8M1_PSWeights_13TeV-powheg-pythia8

### CODE REVIEW

**Review by youyingli — CHANGES_REQUESTED** [review]
Hi @alesauva , two JSONs are accidentally placed outside the campaign directory. Please fix them.

**Comment by alesauva** [comment]
Hi @youyingli , thanks for checking ! It has been fixed. I am still missing 1 final sample so that this PR can be fully merged.

**Review by youyingli — APPROVED** [review]

**Comment by youyingli** [comment]
Hi @alesauva , does this still continue to be updated?  If there are files which are confirmed to have anomalous generator weights, to filter them by setting  "bad": true should be OK.

**Comment by ram1123** [comment]
@youyingli ,

I think in this same pull request we need to add the following two missing samples:

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall18wmLHEGS-04690

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall18wmLHEGS-04691

One of them is just 44% completed.

**Comment by alesauva** [comment]
Hi @youyingli , yes actually the files were succesfully filtered to get rid of such high generator weights (I will push this part in a couple of h), I was waiting for a miniAOD that is not totally written on T2 to be fully there.

**Comment by youyingli** [comment]
Hi @alesauva , all HHtoWWgg should have been included, right?  Of course,  I also see some SM Higgs samples added. If so, the PR is ready to merge !

**Comment by alesauva** [comment]
Hi @youyingli , yes I think everything should be included here. Thanks :)

**Pull request merged**
