### PR TITLE
Add UL2018 campaign

### PR DESCRIPTION
**Pull request by alesauva**
Adding the UL2018 campaign containing the catalogue for different samples:

**Data:
-EGamma**
 /EGamma/Run2018A-12Nov2019_UL2018-v2/
 /EGamma/Run2018B-12Nov2019_UL2018-v2/
/EGamma/Run2018C-12Nov2019_UL2018-v2/
/EGamma/Run2018D-12Nov2019_UL2018-v4/

**-DoubleMuon**
/DoubleMuon/Run2018A-12Nov2019_UL2018-v2
/DoubleMuon/Run2018B-12Nov2019_UL2018-v2
/DoubleMuon/Run2018C-12Nov2019_UL2018-v2
/DoubleMuon/Run2018D-12Nov2019_UL2018-v3

**-Background:**
GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8
 GJet_Pt-20toInf_DoubleEMEnriched_MGG-40to80_TuneCP5_13TeV_Pythia8
GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8
DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8 (1 fille missing less than 0.1 % of events)

**-Signal:**
/GluGluHToGG_M125_TuneCP5_13TeV-amcatnloFXFX-pythia8_storeWeights
/VBFHToGG_M125_TuneCP5_13TeV-amcatnlo-pythia8_storeWeights
/VHToGG_M125_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8
/ttHJetToGG_M125_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8_storeWeights

Adding UL2018 meta-conditions file, remember than only the GT are updated wrt to RR.

Luminosity;
EGamma = 59.816 fb-1
DoubleMuon = 59.802 fb-1

### CODE REVIEW

**Comment by simonepigazzini** [comment]
@rchatter I don't see Legacy 2018 scale and smearings txt files in https://github.com/cms-data/EgammaAnalysis-ElectronTools.git. I believe these are available but maybe only in the new json format?

**Comment by rchatter** [comment]
> @rchatter I don't see Legacy 2018 scale and smearings txt files in https://github.com/cms-data/EgammaAnalysis-ElectronTools.git. I believe these are available but maybe only in the new json format?

Hi Simone,

Indeed for CMS we are trying to switch to something that has been under discussion for a while to have the S+S available from the database, and took a first step for this.
 However at this stage this might be a pain for FLASHgg given that the underlying EnergyScaleCorrection class is also different. Hence like for UL17, will commit the UL18 files in the old format so no other changes are needed in flashGG. Will open a PR with the UL18 MetaConditions having this S+S and keep updating it with the other ingredients.

Thanks,
Rajdeep

**Comment by youyingli** [comment]
Hi @alesauva , the PR is accidentally merged. I have reverted it. Could you please make another PR to continue this PR? Sorry about that.

**Comment by alesauva** [comment]
Hi @youyingli , it seems I cannot make a new PR because it indicates that there is no change found when trying to push from my UL2018 branch...

**Comment by simonepigazzini** [comment]
@alesauva you should backup the catalogue, make a fresh branch from the HEAD of the dev_legacy_runII copy the catalogue and add it to the branch, push + PR. This should work.

btw why was it a problem to merge this?

**Comment by simonepigazzini** [comment]
@alesauva it looks like you added to the repo the QGL file ... remove it please. This usually happens when one runs "git add *" so make sure to avoid that.

**Comment by alesauva** [comment]
Thanks @simonepigazzini I redid the whole procedure and it works.
Indeed I was not careful and pushed added all the changes including the QGL file... Thanks for pointing this out !

**Pull request merged**
