### PR TITLE
Updated correction files for Legacy2016 and Rereco2017

### PR DESCRIPTION
**Pull request by kmondal**
- Added shower shape correction files for Legacy2016 and Rereco2017

- Added stochastic photon isolation correction for Legacy2016

- flashggUpdatedIdMVADiPhotons_cfi.py is updated with new correction files

### CODE REVIEW

**Comment by sethzenz** [comment]
@kmondal The standard tests check out.  I see changes when the photon ID updater is run, which is expected.

Before I accept, can you look into the issue of full5x5_r9 being corrected below 0?  See the flashgg mailing list for discussion.

**Comment by sethzenz** [comment]
Hi @kmondal - is the update here ready?

**Comment by kmondal** [comment]
Hi @sethzenz  as it turns out that pileup reweight was not correct previously for 2017, now I am doing it 
with the updated pileup reweight. I am running a quick final validation now. If everything goes ok, then I will update by tonight. 
Note: only 2017 correction is affected by pileup. Legacy 2016 is okay.

**Comment by sethzenz** [comment]
Tested together with #1017 and changes are only in the places that are expected. Will accept now

**Pull request merged**
