### PR TITLE
adding trigger syst. unc. values for UL 2017 dataset

### PR DESCRIPTION
**Pull request by lfinco**
Adding trigger syst. unc. values for UL 2017 dataset

### CODE REVIEW

**Comment by youyingli** [comment]
Hi @lfinco, could you please point out the reference for the updated trigger SF and unc. ?

**Comment by lfinco** [comment]
Hi @youyingli, if you mean a presentation, you can find the slides here:
https://indico.cern.ch/event/960543/contributions/4040344/attachments/2114628/3557631/HLTEff_STDUL2017_20-10-02_EGM.pdf

**Comment by edjtscott** [comment]
hi @lfinco @youyingli, this should be fine to merge now right?

**Comment by youyingli** [comment]
Hi @edjtscott, yes merge it right now.

**Pull request merged**
