### PR TITLE
additional python configs to run diphoMVA retraining

### PR DESCRIPTION
**Pull request by molmedon**
additional python scripts for running diphoMVA retraining, forgot to add these in a previous pull request .

### CODE REVIEW

**Comment by sethzenz** [comment]
These configurations look like cut-and-paste duplicates of other configurations for dumping the same classes.  I think there must be a more concise way to do this.  The worry is that if any configuration has to change, the more duplicates there are the more changes we'll have to keep track of.

**Comment by molmedon** [comment]
ok, I was just following the model that Yacine and Louie were using. In principle this is not vital for the workflow, but trying to run the dumpers that output the files for the retraining won’t work without them. Do I just keep these in a dedicated branch instead ?



On Jul 16, 2015, at 6:35 PM, Seth Zenz <notifications@github.com<mailto:notifications@github.com>> wrote:


These configurations look like cut-and-paste duplicates of other configurations for dumping the same classes. I think there must be a more concise way to do this. The worry is that if any configuration has to change, the more duplicates there are the more changes we'll have to keep track of.

**Comment by molmedon** [comment]
ah! I think we should be able to put all of them into one config file ?


On Jul 16, 2015, at 7:37 PM, Manuel Alejandro Olmedo Negrete <manuel.alejandro.olmedo.negrete@cern.ch<mailto:manuel.alejandro.olmedo.negrete@cern.ch>> wrote:

ok, I was just following the model that Yacine and Louie were using. In principle this is not vital for the workflow, but trying to run the dumpers that output the files for the retraining won’t work without them. Do I just keep these in a dedicated branch instead ?



On Jul 16, 2015, at 6:35 PM, Seth Zenz <notifications@github.com<mailto:notifications@github.com>> wrote:


These configurations look like cut-and-paste duplicates of other configurations for dumping the same classes. I think there must be a more concise way to do this. The worry is that if any configuration has to change, the more duplicates there are the more changes we'll have to keep track of.

**Comment by sethzenz** [comment]
Accepting, there is a lot of redundancy in the dumpers, but not only in these.  We can clean up later.

**Pull request merged**
