### PR TITLE
Differential cross sections

### PR DESCRIPTION
**Pull request by vtavolar**
This PR contains all the code that is needed to reproduce workspaces/trees for the differential cross sections measurement. 

The code has been kept up-to-date from my side with the flashgg master, but it would be helpful from a technical point of view to have a PR merged to avoid possible divergence of the projects.

I have performed checks before/after merge for standard and differential workspaces against the relevant branches and the number of entries in randomly picked tags is found to be the same. It would be great though if these results could be double-checked for standard workspaces.

Please let me know if you have comments or questions,

Vittorio

### CODE REVIEW

**Comment by sethzenz** [comment]
Have used the web tool to remove a small conflict in one file.  This seems to change how GitHub presents the history, but not to actually change the impact of the PR, so I hope it'll be fine after "squash and merge".

**Comment by sethzenz** [comment]
SigmaMpTTagPreCleanerProducer has to be updated with auto_ptr --> unique_ptr and std::move inside put, as other producers had to be to compile in 92x.  I'll do this in a subsequent PR, after accepting.

**Comment by sethzenz** [comment]
Not able to finish the 92X test today due to https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3789.html   
I'll return when I can.

**Comment by musella** [comment]
Any ETA for merging this?

Thanks,
P.

**Comment by sethzenz** [comment]
As discussed with @vtavolar I will reject this PR.  Then he'll give me a new branch with the latest and greatest from the differential analysis, which I'll take care of rebasing and integrating.

**Pull request closed without merging**
