### PR TITLE
updated to Fall17 EGMID

### PR DESCRIPTION
**Pull request by gkrintir**
hi @sethzenz 

The update to Fall17 EGMID.

Successfully tested the microAOD production with 1000 events.

It would be good to update the README, for an afterbuild is temporarily needed.

### CODE REVIEW

**Comment by sethzenz** [comment]
@gkrintir Can you please remove your changes to LeptonSelection.cc from this PR?  These changes are made automatically in the 94X setup, and making them permanent in the code will break 80X compatibility.

**Comment by gkrintir** [comment]
hi @sethzenz i spotted that but i thought there is an inverse substitution. 
Shouldn't we define one in setup80X ? Otherwise this should be an issue in every PR, no?

**Comment by sethzenz** [comment]
@gkrintir Only if people making the PR's use "git commit -a" to include every file they changed in the PR. :)   Nevertheless, your point is taken that the inverse substitution in 80X is probably easier.  Let's keep things as they are and I'll do the cleanup of the recipes separately.

In the meantime I tested this and confirmed it runs (although not that any particular output is present).  So I'll accept the PR.

**Comment by gkrintir** [comment]
Ok right with "git commit -a" indeed ;D

Ok nice

**Comment by michelif** [comment]
Hi @gkrintir @sethzenz ,
should also this string be update? this is the string wich configures the branch called EGMPhotonMVA in microAOD, which stores the value of the Egamma MVA ID.
(I know because HHbbgg analysis used that branch).
thanks

**Comment by gkrintir** [comment]
hi @michelif 

right, this is done in the customize part:

https://github.com/cms-analysis/flashgg/blob/master/MicroAOD/python/MicroAODCustomize.py#L384

the file you pointed is simply an initialization ;D

**Comment by michelif** [comment]
ah, ok right.
thanks!

**Pull request merged**
