### PR TITLE
Tag moriond17 v8

### PR DESCRIPTION
**Pull request by gkrintir**
Hi @sethzenz  this is the PR for adding PDF weights for the current th samples. There is the addition of 

i)  isThqSample_ in PDFWeightObjectProducer.cc

ii) pdfnlo_weight_container in PDFWeightObject.h to scale our LO prediction to NLO one

### CODE REVIEW

**Comment by sethzenz** [comment]
@gkrintir Thanks for this.  Have you run a test job and confirmed you can get the information back out again from the uAOD?  What about a test job on an ordinary Hgg sample to confirm it still behaves as expected?

**Comment by gkrintir** [comment]
Thanks for asking @sethzenz Indeed, there was a culprit line

https://github.com/gkrintir/flashgg-1/blob/b65e184360b8eb489a8ee753dc552376cd58b7f0/MicroAOD/plugins/PDFWeightObjectProducer.cc#L239

that broke ordinary Hgg sample. Now fixed and I can confirm that PDFWeightObject works both for ordinary Hgg & th samples.

**Comment by gkrintir** [comment]
Hi @sethzenz

Ok so you can verify that the stored weights are identical e.g. taking the two ttH files:

i) before PDFWeightObjectProducer update

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=file%3D%2Fstore%2Fgroup%2Fphys_higgs%2Fcmshgg%2Fsethzenz%2Fflashgg%2FRunIISummer16-2_4_1-25ns_Moriond17%2F2_4_1%2FttHToGG_M125_13TeV_powheg_pythia8_v2%2FRunIISummer16-2_4_1-25ns_Moriond17-2_4_1-v0-RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1%2F170114_093929%2F0000%2FmyMicroAODOutputFile_12.root

ii) after PDFWeightObjectProducer update

https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Fuser%2Fgkrintir%2Fflashgg%2FRunIISummer16-2_4_2-25ns_Moriond17%2F2_4_2%2FttHToGG_M125_13TeV_powheg_pythia8_v2%2FRunIISummer16-2_4_2-25ns_Moriond17-2_4_2-v0-RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1%2F170310_113651%2F0000%2FmyMicroAODOutputFile_12.root&instance=prod%2Fphys03

For the TH samples we also checked that what we need are stored, e.g.

https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Fuser%2Fgkrintir%2Fflashgg%2FRunIISummer16-2_4_2-25ns_Moriond17%2F2_4_2%2FTHQ_HToGG_13TeV-madgraph-pythia8_TuneCUETP8M1%2FRunIISummer16-2_4_2-25ns_Moriond17-2_4_2-v0-RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1%2F170310_184042%2F0000%2FmyMicroAODOutputFile_1.root&instance=prod%2Fphys03

Before merging, let me then erase the last exception in MicroAODCustomize, before the TH samples are fully treated as signal:

https://github.com/gkrintir/flashgg-1/blob/b65e184360b8eb489a8ee753dc552376cd58b7f0/MicroAOD/python/MicroAODCustomize.py#L139-L140

**Comment by sethzenz** [comment]
@gkrintir Sorry for the delay on this PR.  Is it still the latest and greatest?  If so I can go ahead and integrate.  Thanks!

**Comment by gkrintir** [comment]
Hi @sethzenz this one is in deed the latest and greatest ;D

**Pull request merged**
