### PR TITLE
Update diphoton vertexID results for Rereco2017

### PR DESCRIPTION
**Pull request by youyingli**
- Add new training results of diphoton vertex ID and new resolutions of converted photons in Rereco 2017

- Update the codes associated with the validation of diphoton vertex ID

### CODE REVIEW

**Comment by sethzenz** [comment]
Sorry for the delay here.  I'm prioritizing key features for fast track ttH.

**Comment by simonepigazzini** [comment]
@shervin86 @malcles, is there anything we should take from this PR and integrate into the dev_leacy_runII branch?

simone

**Comment by simonepigazzini** [comment]
Please take a look at this @shervin86 @malcles

**Comment by simonepigazzini** [comment]
Further studies are ongoing. I'm closing this PR. If an update is needed to the vertexID a new PR could be made in the future to the legacy runII branch.

**Pull request closed without merging**
